name: Terraform Deploy Timestream

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Plan Terraform changes
      env:
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      run: |
        cd terraform
        terraform plan -out=tfplan

    - name: Apply Terraform changes
      run: |
        cd terraform
        terraform apply tfplan
